// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtTdto2HShDwtezZ2GKxu7wgtM-p_fHs8',
    appId: '1:1031123783517:android:dafc0ae345b87b230962b4',
    messagingSenderId: '1031123783517',
    projectId: 'mvp-vacation-rental',
    databaseURL: 'https://mvp-vacation-rental-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mvp-vacation-rental.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYRf9RUCeOVVvn_atUek07l86EmhmYjaM',
    appId: '1:1031123783517:ios:f78b2813f7b7bb700962b4',
    messagingSenderId: '1031123783517',
    projectId: 'mvp-vacation-rental',
    databaseURL: 'https://mvp-vacation-rental-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mvp-vacation-rental.firebasestorage.app',
    iosClientId: '1031123783517-0qjj958ctd8pl0tdsm6t94o0pkipja41.apps.googleusercontent.com',
    iosBundleId: 'com.triplystays.app',
  );
}
